version: '3.8'

services:
  db:
    image: postgres:15
    container_name: economoney_postgres
    restart: always
    environment:
      POSTGRES_USER: primer
      POSTGRES_PASSWORD: primer
      POSTGRES_DB: economoney_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U botuser -d economoney_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  bot:
    build: .
    container_name: economoney_bot
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "app.py"]